// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTs0oxDSNUxGclTxOvMDhwzPMMe4czDxA',
    appId: '1:892541343597:web:78d81efd10ba682c0dec64',
    messagingSenderId: '892541343597',
    projectId: 'healthy-app-46f2b',
    authDomain: 'healthy-app-46f2b.firebaseapp.com',
    storageBucket: 'healthy-app-46f2b.appspot.com',
    measurementId: 'G-891L0NK7H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC7Ns2EiN7wH_WTwRIWIAQ4y7RVYnQKmQ',
    appId: '1:892541343597:android:ea0efd8fc11a47a70dec64',
    messagingSenderId: '892541343597',
    projectId: 'healthy-app-46f2b',
    storageBucket: 'healthy-app-46f2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7XT5_-44iAV79TgsRoURC-JH_KMLlQmo',
    appId: '1:892541343597:ios:2e1081ef57d7f7010dec64',
    messagingSenderId: '892541343597',
    projectId: 'healthy-app-46f2b',
    storageBucket: 'healthy-app-46f2b.appspot.com',
    iosBundleId: 'com.example.healthyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7XT5_-44iAV79TgsRoURC-JH_KMLlQmo',
    appId: '1:892541343597:ios:12c4adbcc851fb2a0dec64',
    messagingSenderId: '892541343597',
    projectId: 'healthy-app-46f2b',
    storageBucket: 'healthy-app-46f2b.appspot.com',
    iosBundleId: 'com.example.healthyApp.RunnerTests',
  );
}
